org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:/Program Files/Java/jdk-21
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.3
parchment_mappings_version=2024.12.07

minecraft_version=1.21.3
minecraft_version_range=[1.21.3]
neo_version=21.3.96
loader_version_range=[1,)
moddevgradle_version=2.0.141

mod_version=1.0.0
mod_group_id=net.misemise
mod_id=easy_deepslate_mining
mod_name=Easy Deepslate Mining
mod_license=MIT
mod_authors=Misemise
mod_description=Makes deepslate blocks and deepslate ores as easy to mine as regular stone. Perfect for faster mining in the deep dark and underground mining expeditions!
mod_homepage=https://modrinth.com/mod/easy-deepslate-mining

