org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1
minecraft_version_range=[26.1]
neo_version=26.1.0.19-beta
moddevgradle_version=2.0.141

mod_version=1.0.0
mod_group_id=net.misemise
mod_id=easy_deepslate_mining
mod_name=Easy Deepslate Mining
mod_license=MIT
mod_authors=Misemise
mod_description=Makes deepslate blocks and deepslate ores as easy to mine as regular stone. Perfect for faster mining in the deep dark and underground mining expeditions!
mod_homepage=https://modrinth.com/mod/easy-deepslate-mining

